version: '3'
services:
  hub:
    image: selenium/hub:4.10.0
    container_name: selenium-hub
    ports:
      - "4444:4444"
      - "4442:4442"
      - "4443:4443"
    environment:
      - SE_NODE_HOST=selenium-hub
      - SE_NODE_PORT=4444
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443

  chrome:
    image: selenium/node-chrome:4.10.0
    container_name: selenium-node-chrome
    depends_on:
      - hub
    environment:
      - SE_EVENT_BUS_HOST=selenium-hub
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
      - SE_NODE_HOST=selenium-node-chrome
      - SE_NODE_PORT=5555
    volumes:
      - /dev/shm:/dev/shm
    ports:
      - "5555:5555"

  firefox:
    image: selenium/node-firefox:4.10.0
    container_name: selenium-node-firefox
    depends_on:
      - hub
    environment:
      - SE_EVENT_BUS_HOST=selenium-hub
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
      - SE_NODE_HOST=selenium-node-firefox
      - SE_NODE_PORT=5555
    volumes:
      - /dev/shm:/dev/shm
    ports:
      - "5556:5555" 